version: '3.8'

networks:
  web_network:
    driver: bridge

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: transaction-api:0.5.1
    ports:
      - "8080:8080"
    networks:
      - web_network
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./src/main/resources/db:/app/src/main/resources/db
