version: '3.8'

networks:
  web_network:
    driver: bridge

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: transaction-api:0.3
    ports:
      - "8080:8080"
    networks:
      - web_network
    restart: always
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s