spring:
  application:
    name: itau
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_training
    username: x
    password: x
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
